export default {
  title: 'The Circassian Genocide',
  description: 'Discover the history of the largest and most deadly forgotten genocide of the 19th century.',
  about: {
    title: 'Meet The Circassians',
    introduction: {
      title: 'Introduction: Unveiling the Story of the Circassians',
      text: 'The tapestry of global cultures is woven with countless threads, each representing the unique history and heritage of a distinct people. Among these threads are the Circassians, an ancient nation from the North Caucasus whose story, though rich and profound, remains largely unknown to many across the world. Their ancestral homeland, nestled in the strategic region between the Black Sea and the Caspian Sea, bore witness to a vibrant civilization for millennia. Today, the descendants of these people are scattered across the globe, carrying with them the echoes of a powerful past and the enduring spirit of their culture. This page serves as a central resource, inviting individuals from all backgrounds to embark on a journey of discovery into the world of the Circassians, to understand their origins, their traditions, and the significant historical events that have shaped their destiny. For those encountering the name "Circassian" for the first time, this exploration offers an opportunity to learn about a unique culture and a pivotal historical experience that continues to resonate within communities worldwide.',
    },
    origins: {
      title: 'Origins and Ancient Roots: Tracing a History Through Millennia',
      text1: 'The Circassians are deeply rooted in the soil of the North Caucasus, recognized as one of the oldest indigenous populations of this historically significant region. Archaeological research points to the Sinti-Maeotian tribes as the direct ancestors of the present-day Circassians, establishing their presence in the Caucasus from ancient times. Throughout history, this enduring connection to their land has been reflected in various names and mentions. Early Russian sources referred to them as Kasogi, while one theory suggests the modern term "Cherkess" originates from Kerket, the name of an ancient Circassian tribe. The ancient Greeks knew the region as Zichia. The term "Circassian" itself, or "Cherkess" in Russian, has a debated origin, with theories linking it to Turkic languages meaning "head choppers" or "warrior killers," a testament to their martial prowess, or to Mongolian, Persian, or even ancient Greek roots. However, the Circassians themselves identify as "Adyghe," a term that translates to "person of virtue" or "highlander," reflecting their deep connection to the mountainous terrain of their homeland.',
      text2: 'Genetic studies reveal shared ancestry between the Adyghe people and other populations in the Caucasus, including the Ingush, Chechens, Georgians, and Abkhazians, indicating a long history of interaction and shared heritage in this diverse region. Linguistically, the Circassian languages, primarily Adyghe and Kabardian, form a distinct branch within the Northwest Caucasian language family, further highlighting their unique cultural identity. Evidence of early civilization in the region includes the Maikop culture, dating back to 3000 BC, suggesting a sophisticated society with advanced metalworking and artistic traditions. While some researchers have proposed links to even older civilizations like the Hatti, these theories remain a subject of ongoing scholarly debate. Throughout their history, the Circassians engaged in interactions with various external powers, including the Greeks, Romans, Byzantines, and Georgians, leading to the early spread of Christianity in the region.',
      text3: 'Traditionally, Circassian society was organized into a complex tribal structure, with twelve principal tribes often recognized, each symbolized by a star on the Adyghe flag. These tribes, while sharing a common language and cultural heritage, often maintained a degree of autonomy, reflecting the diverse and sometimes fragmented political landscape of the Caucasus. Over the centuries, the Circassians employed various forms of governance, ranging from feudal systems and tribal confederacies to tribal republics and monarchies, demonstrating their capacity for political organization and adaptation to changing circumstances.',
    },
    languageAndCulture: {
      title: 'Language and Cultural Heritage: The Enduring Spirit of a Nation',
      text1: 'The cultural richness of the Circassians is deeply intertwined with their unique linguistic heritage. The Circassian language family comprises two main branches: Adyghe, also known as West Circassian, and Kabardian, or East Circassian. While these two languages are highly mutually intelligible, they exhibit distinct phonetic and lexical differences, leading some linguists to classify them as separate languages. Within Adyghe and Kabardian, a variety of dialects further showcase the linguistic diversity of the Circassian people. This linguistic heritage serves as a vital link to their past and a cornerstone of their cultural identity.',
      text2: 'Central to Circassian culture is Adyghe Xabze, an ancient and comprehensive unwritten code of conduct that governs virtually all aspects of social life. This ethical and philosophical doctrine emphasizes core values such as profound respect for elders and women, the sacred duty of hospitality, unwavering honor, truthfulness, and bravery. Xabze also promotes endogamous marriage as a means of preserving Circassian culture and discourages negative traits like deception and greed while encouraging positive actions such as helping the weak and standing up for the insulted. The thʹamaté, or regional elder, plays a crucial role in interpreting and upholding Xabze, while the Khase, a local advisory council, serves as a community forum for discussing and maintaining these principles.',
      text3: 'Circassian traditions and customs are rich and varied, reflecting a deep respect for social etiquette and community bonds. These include specific rituals surrounding birth and christening, detailed customs for upbringing that emphasize respect and dignity, and elaborate marriage traditions, sometimes involving ritualistic elopement or bride kidnapping. The renowned Circassian hospitality, where guests are treated with utmost care and respect, is a cornerstone of their social fabric.',
      text4: 'The material culture of the Circassians is equally significant. Traditional attire for men includes the Cherkesska, a long coat adorned with decorative bullet pouches, while women wear elegant, intricately embroidered dresses and headscarves, each reflecting social status and tribal affiliation. Their cuisine features fresh, locally sourced ingredients and bold flavors, with popular dishes like shashlik (grilled meat skewers) and chips pasta. Traditional crafts, including intricate metalwork and weaving, are highly valued. The use of Tamgas, unique family stamps or seals, served as symbols of identity and were used to mark possessions and documents, highlighting the importance of lineage and heritage.',
      text5: 'The rich folklore and mythology of the Circassians, passed down through generations, provide insights into their ancient beliefs and values. Their mythology reflects a fascinating blend of pagan beliefs, including the worship of nature and various deities, alongside influences from Christianity and later Islam. The epic tales of the Narts, a mythical race of heroes, are central to their oral tradition, embodying the ideals of courage, honor, and wisdom.',
    },
    war: {
      title: 'The Russo-Circassian Wars and the Genocide: A Century of Resistance and Tragedy',
      text1: 'The 19th century marked a cataclysmic period in Circassian history with the Russo-Circassian Wars, a protracted conflict spanning over a century (1763-1864) that ultimately led to the tragic Circassian Genocide. The Russian Empire, driven by strategic ambitions to secure access to warm water ports and establish a buffer against the Ottoman and Persian empires, embarked on a relentless expansion into the Caucasus region.',
      text2: 'The Circassians mounted a fierce and enduring resistance to this encroachment, employing guerilla warfare tactics in the mountainous terrain of their homeland for over a century. Despite their bravery and determination, the lack of a unified central leadership and the overwhelming military might of the Russian Empire ultimately led to their defeat. The culmination of this conflict witnessed one of the most devastating events in modern history: the Circassian Genocide.',
      text3: 'The Russian Empire implemented a systematic campaign of mass murder, ethnic cleansing, and forced expulsion targeting the Circassian population. Estimates suggest that between 75% and 97% of the Circassian people were either killed outright or forcibly deported from their ancestral lands. The tactics employed by the Russian army were brutal, including mass killings, the burning of villages, the destruction of crops to induce starvation, and forced marches towards the Black Sea coast. The conditions faced by the deportees were horrific, with hundreds of thousands perishing from epidemics, starvation, and the arduous journey across the Black Sea.',
      text4: 'Today, the Russian Federation classifies these events as a "mass migration" and refutes the term genocide. However, the historical evidence and the accounts of survivors paint a clear picture of a systematic effort to eliminate the Circassian people from their homeland. To date, only Georgia and Ukraine have officially recognized the Circassian Genocide. Every year on May 21st, Circassians around the world observe the Circassian Day of Mourning, commemorating the victims and demanding recognition of this historical tragedy.',
    },
    diaspora: {
      title: 'The Global Circassian Diaspora: Scattered Across Continents',
      text1: 'As a direct consequence of the Genocide, the vast majority of Circassians were forced into exile, primarily finding refuge in the Ottoman Empire. The Ottoman authorities often settled these refugees in strategic border regions. Today, the Circassian diaspora is spread across nearly 40 countries, with the largest communities residing in Turkey, which is home to an estimated two to three million people. Significant populations also exist in Jordan, with estimates ranging from 100,000 to 250,000, and Syria, where the community is estimated to be between 80,000 and 120,000. Within the Russian Federation, in the historical homeland, approximately 750,000 Circassians remain, primarily in the republics of Adygea, Kabardino-Balkaria, and Karachay-Cherkessia. Smaller but notable Circassian communities can be found in Israel, Lebanon, the United States (mainly in New Jersey and California), Germany, Egypt, Libya, Iraq, Saudi Arabia, Iran, and various other European nations.',
      text2: 'Despite being dispersed across continents, Circassians in the diaspora have demonstrated remarkable resilience in integrating into their adopted societies while actively working to preserve their unique cultural heritage. Numerous community organizations, cultural centers, and language schools have been established to foster a sense of unity and to transmit the Adyghe language and traditions to younger generations. However, these communities face significant challenges, including the risk of assimilation, language loss as younger generations increasingly adopt the languages of their host countries, and the difficulty of maintaining a distinct cultural identity in diverse environments. For many in the diaspora, there remains a strong desire to return to their ancestral homeland, although various political and bureaucratic obstacles often hinder this aspiration.',
    },
    contributions: {
      title: 'Contributions of Circassians Worldwide: A Legacy of Influence',
      text1: 'Despite the immense challenges they have faced, Circassians have made significant contributions to the societies in which they have settled across the globe. In the Ottoman Empire and its successor state, Turkey, individuals of Circassian origin rose to prominence in various fields, including the bureaucracy, the military (playing a crucial role in the Young Turks movement and the Turkish War of Independence), and intellectual life.',
      text2: 'In Jordan, Circassians are credited with founding modern Amman and have held influential positions in the government, military, and security forces since the establishment of the kingdom. They have also played a vital role as the personal royal guards of the Hashemite monarchs, a tradition that continues to this day. In other parts of the Middle East, including Syria, Egypt, and Israel, Circassians have also made significant contributions, often serving in military and political roles and integrating into various aspects of society.',
    },
    preserving: {
      title: 'Preserving Circassian Identity Today: A Story of Resilience and Hope',
      text1: 'Despite the dispersal and the pressures of assimilation, the preservation of Circassian identity remains a paramount concern for communities worldwide. Within the Russian Federation, in the historical homeland, efforts are underway to safeguard the Adyghe and Kabardian languages and to promote Circassian culture through educational institutions and cultural organizations.',
      text2: 'Across the diaspora, numerous organizations and initiatives are dedicated to this cause. Organizations such as the International Circassian Council (ICC), the Circassian Repatriation Organization (CRO), and the Circassian Benevolent Association (CBA) work to advocate for Circassian rights, preserve cultural heritage, and support diaspora communities. Language preservation is a key focus, with many initiatives aimed at teaching Adyghe and Kabardian to younger generations through community-run schools, online resources, and language exchange programs. The internet and social media have become vital tools for connecting Circassians across geographical boundaries, promoting their culture, and raising awareness about their history. Cultural events and festivals, such as the annual Kafkas Festival in Turkey, play a crucial role in bringing communities together and celebrating their shared heritage through traditional music, dance, and cuisine.',
    },
    connecting: {
      title: 'Connecting with the Circassian Story',
      text1: 'The story of the Circassians is one of ancient origins, a vibrant cultural heritage, a century of tragic conflict, and a remarkable global diaspora. From their ancestral roots in the North Caucasus to their present-day communities scattered across the world, the Circassian people have demonstrated incredible resilience in the face of immense adversity. Understanding their history, especially the devastating impact of the Russo-Circassian Wars and the ensuing Genocide, is crucial for recognizing the importance of human rights, historical justice, and cultural understanding in our interconnected world.',
      text2: 'We invite you to further explore the resources available on this website to delve deeper into specific aspects of Circassian history, culture, and the ongoing efforts to preserve their identity. By learning more and engaging with this story, you contribute to raising awareness and fostering a greater appreciation for the rich tapestry of human experiences that shape our world.',
    },
  },
}
