export default {
  title: 'The Circassian Genocide',
  description: 'Discover the history of the largest and most deadly forgotten genocide of the 19th century.',

  navbar: {
    home: 'Home',
    about: 'About',
    diaspora: 'Diaspora',
    history: 'History',
  },

  // Home page
  home: {
    text1: 'The Circassians are the indigenous people of Circassia, with a history stretching back thousands of years.',
    text2: 'In the 18th and 19th centuries, Tsarist Russia waged a century-long war of extermination, massacring entire villages, burning crops, and replacing the population with settlers from foreign ethnicities.',
    text3: 'The genocide reached its peak in the 1860s — when Circassians were forced on death marches to the Black Sea coast, crammed into ships, and deported.',
    text4: 'In total, over 90% of the Circassian population was either slaughtered, starved, or expelled from their homeland in one of history\'s darkest yet least-known crimes.',
    text5: 'To this day, the Circassians remember this as ЦӀыцӀэкӀун (pronounced Tsitsekun, from the now-extinct Circassian Ubykh language: \'the killing of a people\') and observe May 21 as a global day of mourning—honoring the lives lost and their enduring struggle not for revenge, but for justice.',
    who_we_are: 'Who We Are',
    where_we_are_now: 'Where We Are Now',
    history: 'History',
  },

  // About Page
  about: {
    title: 'Meet The Circassians',
    introduction: {
      title: 'Introduction: Unveiling the Story of the Circassians',
      text: 'The tapestry of global cultures is woven with countless threads, each representing the unique history and heritage of a distinct people. Among these threads are the Circassians, an ancient nation from the North Caucasus whose story, though rich and profound, remains largely unknown to many across the world. Their ancestral homeland, nestled in the strategic region between the Black Sea and the Caspian Sea, bore witness to a vibrant civilization for millennia. Today, the descendants of these people are scattered across the globe, carrying with them the echoes of a powerful past and the enduring spirit of their culture. This page serves as a central resource, inviting individuals from all backgrounds to embark on a journey of discovery into the world of the Circassians, to understand their origins, their traditions, and the significant historical events that have shaped their destiny. For those encountering the name "Circassian" for the first time, this exploration offers an opportunity to learn about a unique culture and a pivotal historical experience that continues to resonate within communities worldwide.',
    },
    origins: {
      title: 'Origins and Ancient Roots: Tracing a History Through Millennia',
      text1: 'The Circassians are deeply rooted in the soil of the North Caucasus, recognized as one of the oldest indigenous populations of this historically significant region. Archaeological research points to the Sinti-Maeotian tribes as the direct ancestors of the present-day Circassians, establishing their presence in the Caucasus from ancient times. Throughout history, this enduring connection to their land has been reflected in various names and mentions. Early Russian sources referred to them as Kasogi, while one theory suggests the modern term "Cherkess" originates from Kerket, the name of an ancient Circassian tribe. The ancient Greeks knew the region as Zichia. The term "Circassian" itself, or "Cherkess" in Russian, has a debated origin, with theories linking it to Turkic languages meaning "head choppers" or "warrior killers," a testament to their martial prowess, or to Mongolian, Persian, or even ancient Greek roots. However, the Circassians themselves identify as "Adyghe," a term that translates to "person of virtue" or "highlander," reflecting their deep connection to the mountainous terrain of their homeland.',
      text2: 'Genetic studies reveal shared ancestry between the Adyghe people and other populations in the Caucasus, including the Ingush, Chechens, Georgians, and Abkhazians, indicating a long history of interaction and shared heritage in this diverse region. Linguistically, the Circassian languages, primarily Adyghe and Kabardian, form a distinct branch within the Northwest Caucasian language family, further highlighting their unique cultural identity. Evidence of early civilization in the region includes the Maikop culture, dating back to 3000 BC, suggesting a sophisticated society with advanced metalworking and artistic traditions. While some researchers have proposed links to even older civilizations like the Hatti, these theories remain a subject of ongoing scholarly debate. Throughout their history, the Circassians engaged in interactions with various external powers, including the Greeks, Romans, Byzantines, and Georgians, leading to the early spread of Christianity in the region.',
      text3: 'Traditionally, Circassian society was organized into a complex tribal structure, with twelve principal tribes often recognized, each symbolized by a star on the Adyghe flag. These tribes, while sharing a common language and cultural heritage, often maintained a degree of autonomy, reflecting the diverse and sometimes fragmented political landscape of the Caucasus. Over the centuries, the Circassians employed various forms of governance, ranging from feudal systems and tribal confederacies to tribal republics and monarchies, demonstrating their capacity for political organization and adaptation to changing circumstances.',
    },
    languageAndCulture: {
      title: 'Language and Cultural Heritage: The Enduring Spirit of a Nation',
      text1: 'The cultural richness of the Circassians is deeply intertwined with their unique linguistic heritage. The Circassian language family comprises two main branches: Adyghe, also known as West Circassian, and Kabardian, or East Circassian. While these two languages are highly mutually intelligible, they exhibit distinct phonetic and lexical differences, leading some linguists to classify them as separate languages. Within Adyghe and Kabardian, a variety of dialects further showcase the linguistic diversity of the Circassian people. This linguistic heritage serves as a vital link to their past and a cornerstone of their cultural identity.',
      text2: 'Central to Circassian culture is Adyghe Xabze, an ancient and comprehensive unwritten code of conduct that governs virtually all aspects of social life. This ethical and philosophical doctrine emphasizes core values such as profound respect for elders and women, the sacred duty of hospitality, unwavering honor, truthfulness, and bravery. Xabze also promotes endogamous marriage as a means of preserving Circassian culture and discourages negative traits like deception and greed while encouraging positive actions such as helping the weak and standing up for the insulted. The thʹamaté, or regional elder, plays a crucial role in interpreting and upholding Xabze, while the Khase, a local advisory council, serves as a community forum for discussing and maintaining these principles.',
      text3: 'Circassian traditions and customs are rich and varied, reflecting a deep respect for social etiquette and community bonds. These include specific rituals surrounding birth and christening, detailed customs for upbringing that emphasize respect and dignity, and elaborate marriage traditions, sometimes involving ritualistic elopement or bride kidnapping. The renowned Circassian hospitality, where guests are treated with utmost care and respect, is a cornerstone of their social fabric.',
      text4: 'The material culture of the Circassians is equally significant. Traditional attire for men includes the Cherkesska, a long coat adorned with decorative bullet pouches, while women wear elegant, intricately embroidered dresses and headscarves, each reflecting social status and tribal affiliation. Their cuisine features fresh, locally sourced ingredients and bold flavors, with popular dishes like shashlik (grilled meat skewers) and chips pasta. Traditional crafts, including intricate metalwork and weaving, are highly valued. The use of Tamgas, unique family stamps or seals, served as symbols of identity and were used to mark possessions and documents, highlighting the importance of lineage and heritage.',
      text5: 'The rich folklore and mythology of the Circassians, passed down through generations, provide insights into their ancient beliefs and values. Their mythology reflects a fascinating blend of pagan beliefs, including the worship of nature and various deities, alongside influences from Christianity and later Islam. The epic tales of the Narts, a mythical race of heroes, are central to their oral tradition, embodying the ideals of courage, honor, and wisdom.',
    },
    war: {
      title: 'The Russo-Circassian Wars and the Genocide: A Century of Resistance and Tragedy',
      text1: 'The 19th century marked a cataclysmic period in Circassian history with the Russo-Circassian Wars, a protracted conflict spanning over a century (1763-1864) that ultimately led to the tragic Circassian Genocide. The Russian Empire, driven by strategic ambitions to secure access to warm water ports and establish a buffer against the Ottoman and Persian empires, embarked on a relentless expansion into the Caucasus region.',
      text2: 'The Circassians mounted a fierce and enduring resistance to this encroachment, employing guerilla warfare tactics in the mountainous terrain of their homeland for over a century. Despite their bravery and determination, the lack of a unified central leadership and the overwhelming military might of the Russian Empire ultimately led to their defeat. The culmination of this conflict witnessed one of the most devastating events in modern history: the Circassian Genocide.',
      text3: 'The Russian Empire implemented a systematic campaign of mass murder, ethnic cleansing, and forced expulsion targeting the Circassian population. Estimates suggest that between 75% and 97% of the Circassian people were either killed outright or forcibly deported from their ancestral lands. The tactics employed by the Russian army were brutal, including mass killings, the burning of villages, the destruction of crops to induce starvation, and forced marches towards the Black Sea coast. The conditions faced by the deportees were horrific, with hundreds of thousands perishing from epidemics, starvation, and the arduous journey across the Black Sea.',
      text4: 'Today, the Russian Federation classifies these events as a "mass migration" and refutes the term genocide. However, the historical evidence and the accounts of survivors paint a clear picture of a systematic effort to eliminate the Circassian people from their homeland. To date, only Georgia and Ukraine have officially recognized the Circassian Genocide. Every year on May 21st, Circassians around the world observe the Circassian Day of Mourning, commemorating the victims and demanding recognition of this historical tragedy.',
    },
    diaspora: {
      title: 'The Global Circassian Diaspora: Scattered Across Continents',
      text1: 'As a direct consequence of the Genocide, the vast majority of Circassians were forced into exile, primarily finding refuge in the Ottoman Empire. The Ottoman authorities often settled these refugees in strategic border regions. Today, the Circassian diaspora is spread across nearly 40 countries, with the largest communities residing in Turkey, which is home to an estimated two to three million people. Significant populations also exist in Jordan, with estimates ranging from 100,000 to 250,000, and Syria, where the community is estimated to be between 80,000 and 120,000. Within the Russian Federation, in the historical homeland, approximately 750,000 Circassians remain, primarily in the republics of Adygea, Kabardino-Balkaria, and Karachay-Cherkessia. Smaller but notable Circassian communities can be found in Israel, Lebanon, the United States (mainly in New Jersey and California), Germany, Egypt, Libya, Iraq, Saudi Arabia, Iran, and various other European nations.',
      text2: 'Despite being dispersed across continents, Circassians in the diaspora have demonstrated remarkable resilience in integrating into their adopted societies while actively working to preserve their unique cultural heritage. Numerous community organizations, cultural centers, and language schools have been established to foster a sense of unity and to transmit the Adyghe language and traditions to younger generations. However, these communities face significant challenges, including the risk of assimilation, language loss as younger generations increasingly adopt the languages of their host countries, and the difficulty of maintaining a distinct cultural identity in diverse environments. For many in the diaspora, there remains a strong desire to return to their ancestral homeland, although various political and bureaucratic obstacles often hinder this aspiration.',
    },
    contributions: {
      title: 'Contributions of Circassians Worldwide: A Legacy of Influence',
      text1: 'Despite the immense challenges they have faced, Circassians have made significant contributions to the societies in which they have settled across the globe. In the Ottoman Empire and its successor state, Turkey, individuals of Circassian origin rose to prominence in various fields, including the bureaucracy, the military (playing a crucial role in the Young Turks movement and the Turkish War of Independence), and intellectual life.',
      text2: 'In Jordan, Circassians are credited with founding modern Amman and have held influential positions in the government, military, and security forces since the establishment of the kingdom. They have also played a vital role as the personal royal guards of the Hashemite monarchs, a tradition that continues to this day. In other parts of the Middle East, including Syria, Egypt, and Israel, Circassians have also made significant contributions, often serving in military and political roles and integrating into various aspects of society.',
    },
    preserving: {
      title: 'Preserving Circassian Identity Today: A Story of Resilience and Hope',
      text1: 'Despite the dispersal and the pressures of assimilation, the preservation of Circassian identity remains a paramount concern for communities worldwide. Within the Russian Federation, in the historical homeland, efforts are underway to safeguard the Adyghe and Kabardian languages and to promote Circassian culture through educational institutions and cultural organizations.',
      text2: 'Across the diaspora, numerous organizations and initiatives are dedicated to this cause. Organizations such as the International Circassian Council (ICC), the Circassian Repatriation Organization (CRO), and the Circassian Benevolent Association (CBA) work to advocate for Circassian rights, preserve cultural heritage, and support diaspora communities. Language preservation is a key focus, with many initiatives aimed at teaching Adyghe and Kabardian to younger generations through community-run schools, online resources, and language exchange programs. The internet and social media have become vital tools for connecting Circassians across geographical boundaries, promoting their culture, and raising awareness about their history. Cultural events and festivals, such as the annual Kafkas Festival in Turkey, play a crucial role in bringing communities together and celebrating their shared heritage through traditional music, dance, and cuisine.',
    },
    connecting: {
      title: 'Connecting with the Circassian Story',
      text1: 'The story of the Circassians is one of ancient origins, a vibrant cultural heritage, a century of tragic conflict, and a remarkable global diaspora. From their ancestral roots in the North Caucasus to their present-day communities scattered across the world, the Circassian people have demonstrated incredible resilience in the face of immense adversity. Understanding their history, especially the devastating impact of the Russo-Circassian Wars and the ensuing Genocide, is crucial for recognizing the importance of human rights, historical justice, and cultural understanding in our interconnected world.',
      text2: 'We invite you to further explore the resources available on this website to delve deeper into specific aspects of Circassian history, culture, and the ongoing efforts to preserve their identity. By learning more and engaging with this story, you contribute to raising awareness and fostering a greater appreciation for the rich tapestry of human experiences that shape our world.',
    },
  },

  // Diaspora Page
  diaspora: {
    title: 'The Circassian Diaspora: Genocide, Exile and Return ',
    description: 'After suffering acts of genocide and ethnic cleansing, Circassians continue to preserve their culture in diaspora in the hopes of reuniting again, one day, at their original homeland.',
    figure_1_caption: 'Circassian Exile Migration Paths to the Ottoman Empire and the Balkans',
    figure_2_caption: 'Circassian Population Distribution Before and After the Genocide',
    figure_3_caption: 'Circassians and Abazins in the Middle East - Instagram: {\'@\'}cactusmapping (https://www.instagram.com/cactusmapping/)',
    beginning: {
      title: 'The Heart of Circassia: Before the Genocide',
      text1: 'The Circassians are recognized historically as the indigenous people of Circassia, who lived in their homeland in the North-Caucasus for thousands of years. Before the Russian invasion, Circassia was a small independent nation. They endured high costs to preserve their identity and defend their homeland in the Caucasus. Circassian society was organized around strong community ties, vibrant cultural traditions, and a deep connection to their mountainous homeland. Their economy thrived on agriculture, craftsmanship, and trade, while their unique language and customs flourished, passed down through generations. Despite external pressures, Circassians maintained their autonomy and rich cultural legacy, defining themselves as resilient and fiercely independent.',
      text2: 'The Circassian population was traditionally divided into multiple tribes, each with its own distinct dialect and regional customs. Major tribes included the Kabardians, Shapsugs, Abzakhs, Bzhedugs, and Hatukuays, spread across strategic areas of the North Caucasus. Geographically, Circassia encompassed the fertile plains and rugged mountain ranges between the Black Sea and the Caspian Sea, extending from the Kuban River in the north to the highlands of the Caucasus Mountains in the south. This unique geography not only influenced their lifestyle but also fortified their stronghold against invasions for centuries.',
      text3: 'The Circassian language, known as "Adyghe," is part of the Northwest Caucasian language family, consisting of two primary dialects: Kabardian (Eastern Adyghe) and Western Adyghe. These dialects reflect the rich linguistic diversity and deep-rooted cultural identity that characterized Circassian life for centuries. Cultural expressions such as dance, music, and storytelling played significant roles in community life, binding families and preserving history. The transmission of folklore and oral traditions kept the spirit of Circassian unity alive, even in times of external threat.',
    },
    exile: {
      title: 'The Diaspora Experience: From Exile to Settlement',
      text1: 'The independence and existence of Circassia were shattered by the Russo-Circassian War. Following their final defeat in 1864, most Circassians were forced into exile. The end of the war in 1864, followed by forced expulsion and genocide led to the tragic reality of the Circassians being dispersed across many geographical and political regions around the world. As a result of the Tsarist exile, the indigenous population of the entire north-western Caucasus was reduced by a massive 94 percent, with less than 10 percent remaining in their homeland.',
      text2: 'Circassians were driven from their homeland and resettled in various areas, including Turkey, Jordan, Syria, Israel, Germany, the United States, Saudi Arabia, Libya, Iraq, Iran, and Egypt. Historically, they also settled in the Balkans (Bulgaria, Kosovo, Romania). In places like the Ottoman Empire, Circassians largely kept to themselves and maintained their separate identity, never forgetting their homeland for which they continually yearned. They established community networks to preserve their culture and heritage amidst foreign surroundings.',
      text3: 'Despite the hardships they faced after being expelled, the Circassians maintained their identity and culture. They built new lives while maintaining their cultural ties, even winning the confidence of those who were supposed to absorb them. For instance, Circassians in Jordan became part of the urban middle class, working in government, military, and intelligence, and gaining significant representation in parliament and the executive branch. They formed a self-image shaped by their experiences as displaced people and as settlers, contributing to their host nations while safeguarding their traditions.',
    },
    today: {
      title: 'Modern Diaspora Dynamics: A Global Network',
      text1: 'Today, significant Circassian diaspora communities exist in numerous countries, including Turkey, Jordan, Syria, Israel, Germany, the United States, Saudi Arabia, Libya, Iraq, Iran, and Egypt. The largest diaspora population is in Turkey, estimated at nearly six million, accounting for almost 80 percent of the overall community. Another source states about 6 million people are diaspora, including 1.5 million citizens of Turkey. In Jordan, an estimated 17% of the community still speaks Adyghe, reflecting strong cultural preservation efforts in the region.',
      text2: 'Circassians in Syria are estimated to be around 1% of the population, and in Israel, they number approximately 4,000-5,000 residing mainly in the villages of Kfar Kama in the Galilee, and Rehaniya. Small, largely urban communities exist in the United States, and there are communities in various European countries. These communities, though scattered, maintain deep connections to their heritage and continue to practice their customs, especially through cultural centers and social gatherings.',
      text3: 'Despite the hardships and the circumstances that affected the diaspora, their bond with their historic homeland and their aspirations for a bright future help them maintain a sense of belonging to their nation. Circassian communities have worked tirelessly to preserve their language, culture, and identity. In diaspora communities, they have established cultural associations and foundations to keep their traditions alive. Advisory councils called "Adyghe Khase" exist globally, serving as unifying bodies that advocate for cultural preservation and community rights.',
    },
    revival: {
      title: 'Cultural Revival: Preserving the Language and Identity',
      text1: 'Preserving the Circassian language and culture is a central part of their identity. It is the principal means whereby social lives are conducted and expresses cultural reality. For Circassians, preserving their native language is considered the main task today, as it is the key to their ethnic identity. However, there are challenges, including assimilation and language loss, which have sparked movements for language revitalization in diaspora communities.',
      text2: 'Despite these challenges, there has been a growing movement for the preservation and development of the Circassian language and traditional culture. Institutions such as Adyghe Khase have been founded to strengthen the Circassian identity within the diaspora. Efforts include devising alphabets, language courses, and the creation of cultural centers aimed at educating the younger generation about their heritage.',
      text3: 'The Circassian diaspora abroad has begun experiencing a cultural reawakening, moving from a spirit of decline towards strength. There is an interest in studying their language and history. Even where full assimilation hasnt occurred, the challenge is gradual assimilation into host societies. Difficulties in saving the language have made it mandatory to depend on other elements of national survival, highlighting the uniqueness of the Circassian identity, which remains alive due to deep cultural roots and strong community solidarity.',
    },
    future: {
      title: 'The Future: Unity and Return to the Homeland',
      text1: 'Circassians continue to organize and engage in political struggles with the dream of living freely and humanely in their historical homeland. They demand international recognition of their historical grievances and current rights. This includes the restoration of their homeland and the acknowledgment of their cultural and political sovereignty.',
      text2: 'There is a growing movement for the recognition of the Circassian Genocide and efforts to reconnect with their ancestral homeland. Repatriation has been a major issue. Circassians are dreaming of returning to their homeland one day. Their plans include the study and defense of Circassian history, and the preservation and multiplication of the Circassian language and identity.',
      text3: 'The idea of "national belonging" allows Circassians to link the past to the present and produce future prospects. Circassian identity elements are affected by not residing in their homeland, with challenges like assimilation and language loss potentially making these factors less effective over time. However, national unity, based on common identity, ancient civilization, common history, and emotional solidarity, supports Circassian solidarity. The Circassian nation remains despite being torn apart, having managed to survive genocide.',
    },
  },

  // Historical Timeline Page
  history: {
    title: 'History: Timeline of the Circassian Genocide',
    introduction: {
      title: 'The Circassians: An Ancient Nation',
      text1: 'The Circassians are an ancient nation. They are historically recognized as the indigenous people of Circassia. Their homeland was located on the northeastern shore of the Black Sea. The Circassians contributed significantly to human civilization. They also endured high costs to preserve their identity in the Caucasus. Before the Russian invasion, Circassia was a small independent nation.',
    },
    war: {
      title: 'The Russo-Circassian War (1763-1864)',
      text1: 'Conflict between Tsarist Russia and the Circassians lasted for over a century, specifically from 1763 to 1864. This prolonged war began with the start of conflicts with Circassia as part of the larger Caucasian War. The war was initiated by Tsarist Russia with the aim of eliminating the presence of the Circassian nation in their homeland and controlling the Circassian Black Sea coast.',
      text2: 'A new strategy for dealing with the northwestern highlanders was summarized by Dmitri Milyutin, chief-of-staff to Bariatinskii, in a policy memorandum in 1857. The idea, according to Milyutin, was not merely to clear the highlands and coastal areas of Circassians for settlement by farmers. Instead, the goal was to make eliminating the Circassians an end in itself – to cleanse the land of hostile elements.',
      text3: 'Tsar Alexander II formally approved this resettlement plan. Milyutin, who later became minister of war, recalled in his memoirs that the plan for 1860 was to "cleanse" (ochistit) the mountain zone of its indigenous population.',
    },
    genocide: {
      title: 'The Circassian Genocide',
      text1: 'The Circassian genocide is also known as Tsitsekun. It refers to the systematic mass killing, ethnic cleansing, and forced displacement of the Circassian people. These actions occurred during the final stages of the Russian invasion in the 19th century.',
      text2: 'Historians and researchers from different countries and times confirm the genocide that the Circassian nation experienced. Walter Richmond argues that the term "genocide" is appropriate for the events of 1864. He describes them as "one of the first examples of modern social engineering". According to Richmond, genocidal intent applies because the demographic transformation of Circassia into a predominantly ethnically Russian region was a desirable outcome for Russian authorities.',
      text3: 'Michael Ellman also agrees that the term "genocide" is justified under the UN definition, which refers to actions intending to destroy an ethnic group in whole or in part.',
      text4: 'The methods used by the Imperial Russian Army included: (1) Mass killings, (2) Impaling victims, (3) Tearing open the bellies of pregnant women to intimidate the Circassians and devastate their morale, (4) Permitting Russian soldiers to rape Circassian women. Generals like Grigory Zass described Circassians as "subhuman filth" and a "lowly race" to justify their wholesale slaughter. Circassians were even used as human test subjects in unethical scientific experiments. ',
    },
    tragedy: {
      title: 'The Scale of the Tragedy: Casualties and Demographic Changes',
      text1: 'The scale of the tragedy during the Russo-Circassian Wars was immense. The genocide resulted in the deaths of a significant portion of the Circassian population. Estimates for the number of deaths range from 1,000,000 to 1,500,000 killed directly or indirectly. An additional 500,000 died whilst fleeing. Some sources indicate approximately 1.5 to 2 million Circassian natives were slaughtered.',
      text2: 'The impact on the Circassian population was devastating. Between 95% and 97% of the Circassian people were either killed outright, died during the military campaigns, or were deported. One estimate shows the indigenous population of the entire north-western Caucasus was reduced by a massive 94 percent. Walter Richmond estimates that with even the most conservative mortality estimates, at least 625,000 Circassians died during Evdokimovs operations alone.',
    },
    exile: {
      title: 'The Great Exile (Deportation)',
      text1: 'Following the genocide, hundreds of thousands more Circassians were forced to leave their homeland. This forced displacement, often referred to as "exile" or "deportation," was a deliberate policy.',
      text2: 'The Circassians were driven from their homeland and deported to the Ottoman Empire over hundreds of raids. Between 1,000,000 and 1,500,000 people were displaced. Approximately 1,500,000 indigenous highland Caucasians were expelled mainly to the Ottoman Empire, with a smaller number sent to Persia.',
      text3: 'Karl Freidrick Neuman cites Ottoman correspondence claiming 1.5 million attempted to sail to Turkey, with 500,000 dying en route, and an additional 500,000 dying from disease in camps on Turkish shores.',
      text4: 'One Circassian delegate articulated the devastating situation during this period, questioning what awaited the displaced migrants forced to go to foreign countries: "How much mercy will the strange countries need to receive hundreds of thousands of immigrants!".',
    },
    diaspora: {
      title: 'Becoming a Stateless People and the Diaspora',
      text1: 'By 1864, after three-fourths of the population had been annihilated, the Circassians had become one of the first stateless peoples in modern history. The forced expulsion resulted in the alienation of ninety percent of the total population from their homeland. This led to a large dispersion across dozens of countries.',
      text2: 'Circassians were resettled in areas including the Balkans, Anatolia, Iraq, and the Levant (Syria, Jordan, Israel). Today, significant Circassian diaspora communities exist in Turkey, Jordan, Syria, Israel, Germany, the United States, Saudi Arabia, Libya, Iraq, Iran, and Egypt, The largest diaspora population resides in Turkey, estimated to be between 2,000,000 and 3,000,000.',
    },
    modernStruggle: {
      title: 'The Modern Struggle',
      text1: 'The Circassian nation seeks justice and the ability to return to their historical homeland. 161 years after being deprived of their right to live and having their resources plundered, they continue their struggle. Resources plundered during the invasion included land, water, fertile soils, cultivation, animals, plants, forests, and minerals. The cultivated Circassian landscape was seen as an indication of civilization.',
      text2: 'There is a modern movement advocating for the rights and freedoms of Circassians. This includes a contemporary struggle to preserve the Circassian language and culture. The campaign for genocide recognition continues.',
      text3: 'Recognition of the genocide, unifying Circassian territories, and the return of the diaspora are main issues on the Circassian movements agenda. Different figures have differing opinions on how to implement these proposals. Documents and facts available need to be presented and published in multiple languages to expose the reality of the genocide and deportation.',
    },
  },
}
