export default {
  title: 'Le Génocide Circassien',
  about: {
    title: 'Les Circassiens : Un Aperçu',
    introduction: {
      title: 'Introduction : Révéler l’Histoire des Circassiens',
      text: 'La tapisserie des cultures mondiales est tissée de fils innombrables, chacun représentant l’histoire et le patrimoine uniques d’un peuple distinct. Parmi ces fils se trouvent les Circassiens, une nation ancienne du Caucase du Nord dont l’histoire, bien que riche et profonde, demeure largement méconnue dans le monde. Leur patrie ancestrale, nichée dans la région stratégique entre la mer Noire et la mer Caspienne, a été le théâtre d’une civilisation florissante pendant des millénaires. Aujourd’hui, les descendants de ce peuple sont dispersés à travers le globe, portant avec eux les échos d’un passé puissant et l’esprit durable de leur culture. Cette page se veut une ressource centrale, invitant les personnes de tous horizons à entreprendre un voyage de découverte du monde des Circassiens, pour comprendre leurs origines, leurs traditions, et les événements historiques majeurs qui ont façonné leur destin. Pour ceux qui entendent le nom "Circassien" pour la première fois, cette exploration offre une opportunité d’apprendre à connaître une culture unique et une expérience historique déterminante qui continue de résonner dans les communautés du monde entier.',
    },
    origins: {
      title:
        'Origines et Racines Anciennes : Une Histoire à Travers les Millénaires',
      text1:
        'Les Circassiens sont profondément enracinés dans le sol du Caucase du Nord, reconnus comme l’une des plus anciennes populations autochtones de cette région historiquement significative. Les recherches archéologiques désignent les tribus Sinti-Maéotiennes comme les ancêtres directs des Circassiens actuels, établissant leur présence dans le Caucase dès les temps anciens. Cette connexion durable à leur terre est reflétée dans divers noms et mentions à travers l’histoire. Les premières sources russes les désignaient sous le nom de Kasogi, tandis qu’une théorie suggère que le terme moderne "Tcherkesse" provient de Kerket, le nom d’une tribu circassienne ancienne. Les Grecs antiques connaissaient la région sous le nom de Zichie. Le terme "Circassien" lui-même, ou "Tcherkesse" en russe, a une origine débattue, certaines théories le liant à des langues turciques signifiant "coupeurs de têtes" ou "tueurs de guerriers", témoignant de leur bravoure martiale, ou à des origines mongoles, perses, voire grecques anciennes. Toutefois, les Circassiens eux-mêmes se désignent sous le nom d’"Adyghe", un terme signifiant "personne vertueuse" ou "montagnard", reflétant leur lien profond avec le relief montagneux de leur terre natale.',
      text2:
        'Des études génétiques révèlent une ascendance commune entre les Adyghe et d’autres populations du Caucase, dont les Ingouches, les Tchétchènes, les Géorgiens et les Abkhazes, indiquant une longue histoire d’interactions et de patrimoine partagé dans cette région diverse. Linguistiquement, les langues circassiennes, principalement l’adyghé et le kabarde, forment une branche distincte de la famille des langues caucasiennes du Nord-Ouest, soulignant davantage leur identité culturelle unique. Des preuves de civilisation ancienne incluent la culture Maïkop, datant de 3000 av. J.-C., suggérant une société sophistiquée avec des traditions avancées de métallurgie et d’artisanat. Bien que certains chercheurs aient proposé des liens avec des civilisations encore plus anciennes comme les Hatti, ces théories restent sujettes à débat académique. À travers leur histoire, les Circassiens ont interagi avec divers pouvoirs extérieurs, dont les Grecs, les Romains, les Byzantins et les Géorgiens, ce qui a mené à une diffusion précoce du christianisme dans la région.',
      text3:
        'Traditionnellement, la société circassienne était organisée en une structure tribale complexe, avec douze tribus principales souvent reconnues, chacune symbolisée par une étoile sur le drapeau adyghe. Ces tribus, tout en partageant une langue et un héritage culturels communs, conservaient souvent un certain degré d’autonomie, reflétant le paysage politique diversifié et parfois fragmenté du Caucase. Au fil des siècles, les Circassiens ont mis en œuvre diverses formes de gouvernance, allant des systèmes féodaux et confédérations tribales aux républiques tribales et monarchies, démontrant leur capacité d’organisation politique et d’adaptation aux circonstances changeantes.',
    },
    languageAndCulture: {
      title: 'Langue et Culture Circassiennes',
      text1:
        'Le peuple adyghe parle les langues circassiennes, principalement l’adyghé (ou adyguéen) et le kabarde, qui font partie de la branche nord-ouest des langues caucasiennes. Ces langues sont réputées pour leurs systèmes phonétiques complexes et leurs consonnes uniques, les distinguant nettement des langues voisines. Malgré les pressions de l’histoire, de nombreuses communautés diasporiques maintiennent leur langue vivante à travers des écoles, des programmes communautaires et les médias numériques.',
      text2:
        'Au cœur de la culture circassienne se trouve l’Adyghe Khabze — littéralement, "la loi ou coutume circassienne". Ce code de conduite régit les interactions sociales, mettant l’accent sur le respect, l’honneur, la générosité et l’hospitalité. L’Adyghe Khabze reflète non seulement les normes éthiques mais aussi l’identité spirituelle et sociale des Circassiens. La musique et la danse jouent un rôle central dans la culture circassienne, la danse Lezginka et la musique jouée au shichepshin (flûte en bois) étant emblématiques. Les danses sont souvent exécutées lors des mariages et des festivals, incarnant la grâce, la force et la discipline.',
      text3:
        'Les Circassiens pratiquaient historiquement diverses religions, y compris une ancienne spiritualité indigène centrée sur le culte des ancêtres et des forces naturelles. Le christianisme s’est propagé parmi eux dès les premiers siècles après J.-C., notamment sous l’influence byzantine. Cependant, à partir du XVIe siècle, l’islam sunnite, notamment dans sa version soufie, s’est progressivement enraciné, devenant majoritaire dans la plupart des régions circassiennes. Aujourd’hui, l’héritage religieux des Circassiens reste varié, avec des éléments traditionnels intégrés à la pratique islamique.',
    },
    war: {
      title: 'La Guerre Russo-Circassienne : Résistance et Tragédie',
      text1:
        'La guerre russo-circassienne (1763–1864) représente l’un des conflits les plus longs et les plus tragiques du XIXe siècle. Déclenchée par l’expansion impériale russe vers le sud, elle fut marquée par une résistance farouche des Circassiens à la domination étrangère. Ce conflit de plus d’un siècle a été marqué par des tactiques militaires brutales, des campagnes de terre brûlée et des attaques systématiques contre la population civile.',
      text2:
        'Les Circassiens, malgré leur division en tribus et l’absence d’un État centralisé, ont mené une résistance remarquable à travers des tactiques de guérilla et une connaissance intime du terrain montagneux. Des figures légendaires comme Hajretbi Marzukan, Shamil ou Qerandiqo Berzeg ont émergé comme symboles de courage et de résilience. Cependant, en raison de la supériorité militaire russe et du manque de soutien international, la résistance circassienne finit par s’effondrer au milieu du XIXe siècle.',
      text3:
        'La fin de la guerre en 1864 fut marquée par un événement cataclysmique : le génocide et la déportation massive des Circassiens. Des centaines de milliers de civils furent tués, et plus de 90 % de la population restante fut forcée à l’exil, principalement vers l’Empire ottoman. Les déportations se firent dans des conditions inhumaines, causant des famines, des maladies et la mort en masse. De nombreux historiens et chercheurs considèrent ces événements comme l’un des premiers génocides modernes, un acte délibéré visant à effacer une nation de sa terre ancestrale.',
    },
    diaspora: {
      title: 'Diaspora et Héritage : Une Nation Dispersée',
      text1:
        'Suite à leur expulsion du Caucase, les Circassiens ont trouvé refuge dans divers territoires de l’Empire ottoman, notamment en Turquie, en Syrie, en Jordanie et dans d’autres parties du Moyen-Orient. Plus tard, des communautés se sont également établies en Europe occidentale, en Amérique du Nord et récemment en Israël. Cette diaspora, bien que dispersée, reste profondément attachée à son identité et à ses racines culturelles.',
      text2:
        'Dans de nombreuses régions, les Circassiens ont joué des rôles clés dans les sociétés hôtes — en tant que militaires, administrateurs, intellectuels et artistes. Leur capacité d’adaptation et leur forte cohésion communautaire leur ont permis de préserver leur langue, leurs traditions et leur mémoire historique malgré les défis de l’exil.',
      text3:
        'Aujourd’hui, les communautés diasporiques continuent de plaider pour la reconnaissance du génocide, la préservation de leur culture et, dans certains cas, le droit au retour dans leur patrie ancestrale. En Russie même, les républiques adyghes (Adyguée, Karatchaïévo-Tcherkessie, Kabardino-Balkarie) abritent encore des Circassiens, bien que leur nombre soit nettement réduit. La renaissance culturelle actuelle est soutenue par des ONG, des institutions éducatives, et des initiatives numériques visant à revitaliser la langue et la mémoire collective.',
    },
    contributions: {
      title:
        'Contributions des Circassiens à Travers le Monde : Un Héritage d\'Influence',
      text1:
        'Malgré les immenses défis auxquels ils ont été confrontés, les Circassiens ont apporté des contributions significatives aux sociétés dans lesquelles ils se sont installés à travers le monde. Dans l’Empire ottoman et son État successeur, la Turquie, des individus d’origine circassienne se sont distingués dans divers domaines, notamment la bureaucratie, l’armée (jouant un rôle crucial dans le mouvement des Jeunes-Turcs et la guerre d’indépendance turque) et la vie intellectuelle.',
      text2:
        'En Jordanie, les Circassiens sont reconnus pour avoir fondé la ville moderne d’Amman et ont occupé des postes influents dans le gouvernement, l’armée et les forces de sécurité depuis la création du royaume. Ils ont également joué un rôle vital en tant que gardes personnels des monarques hachémites, une tradition qui se perpétue encore aujourd’hui. Dans d’autres régions du Moyen-Orient, notamment en Syrie, en Égypte et en Israël, les Circassiens ont également contribué de manière significative, souvent en servant dans les sphères militaires et politiques et en s’intégrant dans divers aspects de la société.',
      text3:
        'Dans de nombreux domaines, plusieurs figures célèbres d’origine circassienne ont marqué le monde moderne. Parmi elles figurent des personnalités de la littérature comme le lauréat du prix Nobel Orhan Pamuk, le célèbre poète Nâzım Hikmet, et l’écrivain influent Amjad Jaimoukha. Dans les arts, Ludmilla Tchérina s’est illustrée comme danseuse de ballet de renommée internationale, tandis qu’au cinéma, des acteurs comme Rushdy Abaza et des actrices telles que Türkan Şoray ont laissé une empreinte durable. Le sport a également vu émerger des talents circassiens tels que le lutteur Yaşar Doğu, champion olympique, et le footballeur Bibras Natcho, capitaine de l’équipe nationale israélienne. Cette liste, bien que non exhaustive, illustre la diversité des talents et des réalisations des Circassiens au fil de l’histoire et dans le monde contemporain.',
    },
    preserving: {
      title:
        'Préserver l’Identité Circassienne Aujourd’hui : Une Histoire de Résilience et d’Espoir',
      text1:
        'Malgré la dispersion et les pressions assimilatrices, la préservation de l’identité circassienne demeure une priorité pour les communautés à travers le monde. Au sein de la Fédération de Russie, dans la patrie historique, des efforts sont déployés pour sauvegarder les langues adyghé et kabarde et promouvoir la culture circassienne par le biais d’institutions éducatives et d’organisations culturelles.',
      text2:
        'Dans la diaspora, de nombreuses organisations et initiatives se consacrent à cette mission. Des entités comme le Conseil International Circassien (ICC), l’Organisation de Rapatriement Circassienne (CRO) et l’Association de Bienfaisance Circassienne (CBA) œuvrent pour la défense des droits circassiens, la préservation du patrimoine culturel, et le soutien aux communautés diasporiques. La sauvegarde linguistique est au cœur des préoccupations, avec de nombreuses initiatives visant à enseigner l’adyghé et le kabarde aux jeunes générations, grâce à des écoles communautaires, des ressources en ligne et des programmes d’échange linguistique. Internet et les réseaux sociaux sont devenus des outils essentiels pour connecter les Circassiens au-delà des frontières, promouvoir leur culture et sensibiliser à leur histoire. Les événements et festivals culturels, comme le festival annuel Kafkas en Turquie, jouent un rôle crucial en réunissant les communautés et en célébrant leur héritage commun à travers la musique, la danse et la cuisine traditionnelles.',
    },
    connecting: {
      title: 'Se Connecter à l’Histoire Circassienne',
      text1:
        'L’histoire des Circassiens est celle d’origines anciennes, d’un patrimoine culturel vibrant, d’un siècle de conflits tragiques et d’une diaspora mondiale remarquable. De leurs racines ancestrales dans le Caucase du Nord à leurs communautés actuelles dispersées à travers le monde, les Circassiens ont fait preuve d’une résilience extraordinaire face à l’adversité. Comprendre leur histoire, en particulier l’impact dévastateur des guerres russo-circassiennes et du génocide qui a suivi, est essentiel pour reconnaître l’importance des droits humains, de la justice historique et de la compréhension interculturelle dans notre monde interconnecté.',
      text2:
        'Nous vous invitons à explorer davantage les ressources disponibles sur ce site afin d’approfondir votre connaissance de l’histoire, de la culture et des efforts actuels de préservation de l’identité circassienne. En apprenant et en vous engageant dans cette histoire, vous contribuez à sensibiliser le public et à valoriser la richesse des expériences humaines qui façonnent notre monde.',
    },
  },
}
